baseURL: https://gusanzheng.github.io/
languageCode: en-us
title: Elvin's Blog
pagination.pagierSize: 5
theme: PaperMod

buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true

minify:
  disableXML: true
  minifyOutput: true

params:
  DateFormat: "2006/01/02"
  defaultTheme: auto
  ShowToc: true
  TocOpen: true
  ShowWordCount: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  comments: true
  VisitCount: true
  ShowLastMod: true #显示文章更新时间

  assets:
    favicon: "panda.png"
    favicon16x16: "panda.png"
    favicon32x32: "panda.png"
    apple_touch_icon: "panda.png"
    safari_pinned_tab: "panda.png"

  label:
    text: "🐼 Elvin' Blog"

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to Elvin's Blog

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/gusanzheng"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
    includeMatches: true
  
  # for comment
  # https://giscus.app/
  # https://www.lixueduan.com/posts/blog/02-add-giscus-comment/
  giscus:
    repo: "gusanzheng/blog"
    repoId: "R_kgDONg89Hg"
    category: "Announcements"
    categoryId: "DIC_kwDONg89Hs4CleBn"
    mapping: "pathname"
    strict: "0"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "bottom"
    theme: "preferred_color_scheme"
    lang: "en"
    crossorigin: "anonymous"
  
  # https://blog.kanikig.xyz/hugo-busuanzi/
  busuanzi:
    enable: true


menu:
  main:
    - identifier: home
      name: 🏠 Home
      url: /
      weight: 10
    - identifier: posts
      name: 📚️ Posts
      url: posts
      weight: 20
    - identifier: archives
      name: 🕙️ Archives
      url: archives
      weight: 30
    - identifier: tags
      name: 🧩 Tags
      url: /tags/
      weight: 40
    - identifier: search
      name: 🔍 Search
      url: /search/
      weight: 50

markup:
  highlight:
    noClasses: false
    guessSyntax: true
    anchorLineNos: false # 不要给行号设置锚标
    codeFences: true # 代码围栏
    lineNos: true # 代码行
    lineNumbersInTable: false
    style: darcula

# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
    - HTML # 生成的静态页面
    - RSS # 这个其实无所谓
    - JSON # necessary for search, 这里的配置修改好之后，一定要重新生成一下