on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  hugo-build:
    name: hugo build
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 构建 web
      run: |
        go version
        go install github.com/gohugoio/hugo@latest
        export PATH=$PATH:/home/runner/go/bin
        hugo version
        hugo
        ls public
    
    - name: 部署 web
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: web
        folder: public
